apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-search-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main
        image: hesh11/my_repository-1:latest
        ports:
        - containerPort: 8080
